POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "020202",
  "password": "020202"
}

###

POST http://localhost:3000/dashboard/create
Content-Type: application/json

{
    "name": "Aeris",
    "carplate": "ABC1234",
    "identification": "1234567890",
    "mobile": "0123456789",
    "visitpurpose": "Meeting"
}

###
GET http://localhost:3000/dashboard/

###
GET http://localhost:3000/dashboard/pending

###
GET http://localhost:3000/dashboard/approved

###
GET http://localhost:3000/dashboard/rejected

###
GET http://localhost:3000/dashboard/history

###
POST http://localhost:3000/dashboard/approve
Content-Type: application/json

{
  "_id": "20231224223844"
}

###
POST http://localhost:3000/dashboard/reject
Content-Type: application/json

{
  "_id": "20231224223607",
  "reason": "Not a good guy"
}

###
GET http://localhost:3000/logout

###